# Generated by Django 5.2.13 on 2026-05-24 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedido',
            new_name='fecha_hora_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo para Recojo'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='franja_recojo',
            field=models.CharField(choices=[('MAÑANA', 'Mañana (09:00 AM - 01:00 PM)'), ('TARDE', 'Tarde (01:00 PM - 06:00 PM)'), ('NOCHE', 'Noche (06:00 PM - 09:00 PM)')], default='MAÑANA', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.producto'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('BILLETERA DIGITAL', 'Yape / Plin'), ('EFECTIVO', 'Efectivo en Tienda'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(default='APROBADO_SIMULADO', max_length=20)),
                ('referencia_transaccion', models.CharField(max_length=50, unique=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido')),
            ],
        ),
    ]
