# Generated by Django 5.2.13 on 2026-06-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_fecha_pedido_pedido_fecha_hora_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'PLin'), ('EFECTIVO', 'Efectivo en Tienda'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito / Débito (Stripe)')], max_length=20),
        ),
    ]
