# Generated by Django 5.2.13 on 2026-06-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'PLin'), ('EFECTIVO', 'Efectivo en Tienda'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('STRIPE', 'Tarjeta de Crédito / Débito (Stripe)')], max_length=20),
        ),
    ]
