# Generated by Django 5.2.13 on 2026-06-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Billeteras Digitales', [('LOCAL_YAPE', 'Yape (Simulación Local)'), ('LOCAL_PLIN', 'Plin (Simulación Local)'), ('STRIPE_WALLET', 'Google Pay / Apple Pay / Link (Stripe)')]), ('Tarjetas', [('STRIPE_CARD', 'Tarjeta de Crédito / Débito (Stripe)')]), ('Otros Métodos', [('LOCAL_EFECTIVO', 'Efectivo en Tienda'), ('LOCAL_TRANSFERENCIA', 'Transferencia Bancaria')])], max_length=20),
        ),
    ]
