# Generated by Django 5.2.13 on 2026-07-02 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_stock_reservado'),
        ('pedidos', '0005_alter_pago_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RECOJO', 'Recojo en Tienda (Gratis)'), ('DELIVERY', 'Delivery a Domicilio (+ S/ 10.00)')], default='RECOJO', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Pago en Línea Segura', [('STRIPE_CARD', 'Tarjeta de Crédito / Débito (Stripe)'), ('STRIPE_WALLET', 'Google Pay / Apple Pay / Link (Stripe)'), ('LOCAL_YAPE', 'Yape / Plin (Simulación Online)')]), ('Pago Contra Entrega (Físico)', [('CONTRA_EFECTIVO', 'Pago en Efectivo'), ('CONTRA_TARJETA', 'Pago con Tarjeta (POS)'), ('CONTRA_BILLETERA', 'Pago con Yape/Plin (QR)')])], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'En Preparación'), ('LISTO', 'Listo para Recojo/Envío'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='franja_recojo',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana (8:00 AM - 12:00 PM)'), ('TARDE', 'Tarde (12:00 PM - 4:00 PM)'), ('NOCHE', 'Noche (4:00 PM - 8:00 PM)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
