# Generated by Django 5.2.13 on 2026-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_reservado',
            field=models.IntegerField(default=0),
        ),
    ]
