"""
Django settings for minimarket project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3-y5)*l4g3541wzcmom8dhb2@y=j1fpj)96_j7#wu#+i@0#vl='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.catalogo',
    'apps.pedidos',
    'apps.usuarios', # Nueva app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minimarket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minimarket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Se utiliza para imprimir los correos electrónicos enviados en la consola (terminal) 
# en lugar de enviarlos realmente por SMTP
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# CONFIGURACIONES DE AUTENTICACIÓN
LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = 'catalogo:lista_productos' # A donde va al iniciar sesión
LOGOUT_REDIRECT_URL = 'catalogo:lista_productos' # A donde va al cerrar sesión
# El cliente tiene 15 minutos (900 segundos) para pagar antes de perder su reserva
# SESSION_COOKIE_AGE = 900
# AÑADE esta nueva variable personalizada al final del archivo:
# Tiempo de inactividad permitido para el carrito en segundos (Pon 10 para probar, luego cámbialo a 900)
CARRITO_TIEMPO_VIDA = 900
# CONFIGURACIÓN DE STRIPE
STRIPE_PUBLIC_KEY = 'pk_test_51Tkpd4E8lq5RChCCVKCi9vVXs9DW4nHhzgLaXJMno6305Tz4xuc9FsSOZvkQOvEjyiCVvGQxIfLb8vG8O5U4ymdE00KzyYKC8z'
STRIPE_SECRET_KEY = 'sk_test_51Tkpd4E8lq5RChCChkxJw5g4kwaBQjxxAOBAYNOkAGHKB2SOV5UvCN2pa6I6QePB8amucQePu2V4kES4R4dEyLBI00B7x6IUTv'